# Generated by Django 5.0.2 on 2024-03-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('entreprise', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
    ]
